'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class MiConexion
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=MiConexion")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Ciudads() As DbSet(Of Ciudad)
    Public Overridable Property Personas() As DbSet(Of Persona)
    Public Overridable Property sysdiagrams() As DbSet(Of sysdiagram)

End Class
