'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Ciudad
    Public Property id As Integer
    Public Property nombre As String
    Public Property estado As Nullable(Of Boolean)

    Public Overridable Property Personas As ICollection(Of Persona) = New HashSet(Of Persona)

End Class
