'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Persona
    Public Property id As Integer
    Public Property primerNombre As String
    Public Property segundoNombre As String
    Public Property primerApellido As String
    Public Property segundoApellido As String
    Public Property fechaNac As Date
    Public Property sexo As Nullable(Of Boolean)
    Public Property telefono As String
    Public Property email As String
    Public Property idCiudad As Nullable(Of Integer)
    Public Property direccion As String
    Public Property estado As Nullable(Of Boolean)

    Public Overridable Property Ciudad As Ciudad

End Class
